# Generated by Django 2.2.7 on 2024-05-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('gst_number', models.CharField(max_length=20, null=True)),
                ('pan_number', models.CharField(max_length=15, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.Vendor')),
            ],
        ),
    ]
